## TODO: Modularize the gitlab yaml to reuse templates

## Define the stages & order of execution

stages:
  - CLUSTER-STATE
  - PROVIDER-INFRA-SETUP
  - STATEFUL-APP-DEPLOY
#  - APP-FUNC-TEST
#  - APP-CHAOS-TEST
  - CLUSTER-CLEANUP

OS-3.10-EE:
  image: atulabhi/kops:v8
  stage: CLUSTER-STATE
  script:
   - echo "PIPELINEMODE=$CI_PIPELINE_SOURCE"
   - chmod 775 ./scripts/providers/cluster-state
   - ./scripts/providers/cluster-state

openebs-0.8.1:
  image: atulabhi/kops:v8
  stage: PROVIDER-INFRA-SETUP
  before_script:
   - chmod 775 ./scripts/providers/infra-setup
   - ./scripts/providers/infra-setup pod
  script:
   - chmod 775 ./scripts/providers/cstor-disk-provision
   - ./scripts/providers/cstor-disk-provision pod 
  dependencies:
    - OS-3.10-EE

.app_deploy_template:
  image: atulabhi/kops:v8
  stage: STATEFUL-APP-DEPLOY 
  dependencies:
    - openebs-0.8.1

busybox-cstor:
  extends: .app_deploy_template
  script: 
   - chmod 755 ./scripts/apps/busybox/busybox-app-deploy-cstor
   - ./scripts/apps/busybox/busybox-app-deploy-cstor pod

#cassandra-cstor:
#  extends: .app_deploy_template   
#  script: 
#   - chmod 755 ./scripts/apps/cassandra/cassandra-app-deploy-cstor
#   - ./scripts/apps/cassandra/cassandra-app-deploy-cstor pod

#.func_test_template:
#  image: atulabhi/kops:v8
#  stage: APP-FUNC-TEST
#  when: always 

#app-replica-scale-{cassandra-cstor}:
#  extends: .func_test_template #dependencies: cassandra-cstor
#  script:
#    - chmod 775 ./scripts/apps/cassandra/functional/cstor/app-sts-replica-scale
#    - ./scripts/apps/cassandra/functional/cstor/app-sts-replica-scale  
#

#.chaos_test_template:
#  image: atulabhi/kops:v8
#  stage: APP-CHAOS-TEST
#  when: always


#tgt-kill-{percona-cstor}:
#  extends: .chaos_test_template #dependencies: percona-cstor
#  script:
#    - chmod 775 ./scripts/apps/percona/chaos/cstor/volume-target-failure
#    - ./scripts/apps/percona/chaos/cstor/volume-target-failure

cluster-cleanup:
  image: atulabhi/kops:v8
  stage: CLUSTER-CLEANUP
  dependencies:
    - OS-3.10-EE
  script:
    - chmod 775 ./scripts/providers/cluster-cleanup
    - ./scripts/providers/cluster-cleanup pod
