#!/bin/bash
set -x

pod() {
apt-get install sshpass

sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd mdap-e2e-staging && bash scripts/providers/cluster-cleanup node'
}

node() {
echo "*******Reverting back to Healthy cluter state***************"
present_dir=$(pwd)
echo $present_dir

ansible-playbook litmus/k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv
cd ..rm -rf mdap-e2e-staging
echo "********CLUSTER REVERTED*********************"
}
